var georgeWashingtonStory = "George Washington is arguably the best known of the founding fathers, but few people are aware of his {{adjective}} childhood. From an early age it was clear to see that George was destined for military greatness when he and his best friend the {{adjective}} {{noun}}, {{adverb}} defeated the {{adjective}} {{noun}} in a small skirmish outside of school. Other accounts tell of the way George used to {{adverb}} {{verb}}, {{verb}} and {{verb}} around the yard in his boyhood military uniform while {{adverb}} {{verb}}ing Charles, his pet {{noun}} the whole time. Though he was later to {{adverb}} become one of the greatest men in US history, we should never forget that George Washington started his life as nothing more than a short and slightly {{adjective}} {{noun}}.";

var abrahamLincolnStory = "Abraham Lincoln is arguably one of the best known of the United States presidents, but few people are aware of his {{adjective}} childhood. From an early age it was clear to see that Abraham was destined for leadership when he and his best friend the {{adjective}} {{noun}}, {{adverb}} gave a speech that was so moving it left the {{adjective}} {{noun}} in tears. Other accounts tell of the way Abraham used to {{adverb}} {{verb}}, {{verb}} and {{verb}} around the yard in his boyhood black suit and tophat, while {{adverb}} {{verb}}ing Charles, his pet {{noun}} the whole time. Though he was later to {{adverb}} become one of the greatest men in US history, we should never forget that Abraham Lincoln started his life as nothing more than a freakishly tall and slightly {{adjective}} {{noun}}.";

var marieCurieStory = "Marie Curie is arguably one of the best known women in history, but few people are aware of her {{adjective}} childhood. From an early age it was clear to see that young Marie was destined for inspired work in the field of biology, when her and her best friend the {{adjective}} {{noun}}, {{adverb}} used an at-home chemistry set to cure their neighbor  the {{adjective}} {{noun}} of his severe skin infection. Other accounts tell of the way Marie used to {{adverb}} {{verb}}, {{verb}} and {{verb}} around the yard in with her wagon full of biology books, while {{adverb}} {{verb}}ing Charles, her pet {{noun}} the whole time. Though she was later to {{adverb}} become one of the greatest biologists in history, we should never forget that Marie Curie started her life as nothing more than a shy and slightly {{adjective}} {{noun}}.";

var randomNoun = ['mountain', 'bobcat', 'chair', 'piano', 'pillowcase', 'printer', 'skyscraper', 'ball of cheese', 'stick', 'garbagecan'];
var randomVerb = ['eat', 'devour', 'stare', 'climb', 'jump', 'kill', 'poop', 'listen', 'flip out', 'stop'];
var randomAdjective = ['tall', 'dark', 'short', 'evil', 'misunderstood', 'formidable', 'tempestuouse', 'sketchy', 'ugly', 'beautiful'];
var randomAdverb = ['lovingly', 'sarcastically', 'stupidly', 'wisely', 'arrogantly', 'quickly', 'loosley', 'underhandedly', 'decisevely', 'athletically'];